spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newss?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123
    driverClassName: com.mysql.jdbc.Driver
